services:
  mysql:
    image: mysql:8.0
    container_name: redi-orm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s
    volumes:
      - mysql_data:/var/lib/mysql

  postgresql:
    image: postgres:15
    container_name: redi-orm-postgresql
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      timeout: 10s
      retries: 5
      interval: 10s
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: redi-orm-mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: testdb
    healthcheck:
      test: |
        echo 'try { rs.status().ok } catch (e) { rs.initiate({_id:"rs0",members:[{_id:0,host:"localhost:27017"}]}) }' | mongosh --quiet || exit 1
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  postgresql_data:
  mongodb_data: