name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Semantic versioning tags (e.g., v1.0.0, v2.1.3)

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  GO_VERSION: '1.21'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64  # Windows ARM64 excluded for practicality

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Download dependencies
      run: go mod download

    - name: Build redi-orm binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        # Define binary name with platform suffix
        BINARY_NAME="redi-orm"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        BINARY_NAME="${BINARY_NAME}-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        # Build binary with version injection
        go build -o "${BINARY_NAME}" \
          -ldflags "-s -w -X main.version=${{ env.VERSION }}" \
          ./cmd/redi-orm
        
        # Verify binary was created and works
        if [ "${{ matrix.goos }}" != "windows" ]; then
          ./"${BINARY_NAME}" version || echo "Binary test failed, but continuing..."
        fi
        
        echo "ORM_BINARY_NAME=${BINARY_NAME}" >> $GITHUB_ENV

    - name: Build redi-mcp binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        # Define binary name with platform suffix
        BINARY_NAME="redi-mcp"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        BINARY_NAME="${BINARY_NAME}-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        # Build binary with version injection
        go build -o "${BINARY_NAME}" \
          -ldflags "-s -w -X main.version=${{ env.VERSION }}" \
          ./cmd/redi-mcp
        
        # Verify binary was created and works
        if [ "${{ matrix.goos }}" != "windows" ]; then
          ./"${BINARY_NAME}" version || echo "Binary test failed, but continuing..."
        fi
        
        echo "MCP_BINARY_NAME=${BINARY_NAME}" >> $GITHUB_ENV

    - name: Create archives
      run: |
        # Create platform-specific archives for both binaries
        if [ "${{ matrix.goos }}" = "windows" ]; then
          # Windows: ZIP archives
          zip "redi-orm-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "${ORM_BINARY_NAME}"
          zip "redi-mcp-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "${MCP_BINARY_NAME}"
          echo "ORM_ARCHIVE_NAME=redi-orm-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip" >> $GITHUB_ENV
          echo "MCP_ARCHIVE_NAME=redi-mcp-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip" >> $GITHUB_ENV
        else
          # Unix: TAR.GZ archives
          tar -czf "redi-orm-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" "${ORM_BINARY_NAME}"
          tar -czf "redi-mcp-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" "${MCP_BINARY_NAME}"
          echo "ORM_ARCHIVE_NAME=redi-orm-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" >> $GITHUB_ENV
          echo "MCP_ARCHIVE_NAME=redi-mcp-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" >> $GITHUB_ENV
        fi

    - name: Generate checksums
      run: |
        # Generate SHA256 checksums for both archives
        if command -v sha256sum >/dev/null; then
          sha256sum "${ORM_ARCHIVE_NAME}" > "${ORM_ARCHIVE_NAME}.sha256"
          sha256sum "${MCP_ARCHIVE_NAME}" > "${MCP_ARCHIVE_NAME}.sha256"
        elif command -v shasum >/dev/null; then
          shasum -a 256 "${ORM_ARCHIVE_NAME}" > "${ORM_ARCHIVE_NAME}.sha256"
          shasum -a 256 "${MCP_ARCHIVE_NAME}" > "${MCP_ARCHIVE_NAME}.sha256"
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-assets-${{ matrix.goos }}-${{ matrix.goarch }}
        path: |
          *.zip
          *.tar.gz
          *.sha256
        retention-days: 1

  create-release:
    name: Create GitHub Release
    needs: release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: release-assets-*
        path: ./release-assets
        merge-multiple: true

    - name: Generate release notes
      id: release_notes
      run: |
        cat > release_notes.md << 'EOF'
        # RediORM ${{ env.VERSION }}

        ## What's New
        
        This release includes both the RediORM CLI tool and the MCP (Model Context Protocol) server for AI assistant integration.

        ## 🚀 RediORM CLI Features

        - **Multi-database support**: SQLite, MySQL, PostgreSQL, MongoDB
        - **Prisma-style schema definitions**: Familiar and powerful schema syntax
        - **JavaScript runtime**: Execute database operations using JavaScript with ORM support
        - **Migration system**: Auto-migration for development, file-based migrations for production
        - **Transaction support**: Full ACID transactions with savepoints
        - **Relation support**: One-to-one, one-to-many, many-to-many relations with eager loading
        - **GraphQL & REST APIs**: Auto-generated APIs from your schema
        - **Raw query support**: Execute custom SQL when needed

        ## 🤖 RediORM MCP Features

        - **AI Integration**: Enable AI assistants to understand and interact with your database
        - **Natural Language Queries**: AI can process requests like "find all users who posted this week"
        - **Schema Understanding**: AI comprehends your data model relationships and constraints
        - **Safe Operations**: Read-only mode by default, with granular permission control
        - **Multiple Modes**: Stdio mode for Claude Desktop, HTTP streaming mode for Cursor/Windsurf

        ## Installation

        ### Download and Extract

        Choose the appropriate binary for your platform:

        **Linux (AMD64)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-orm-${{ env.VERSION }}-linux-amd64.tar.gz
        tar -xzf redi-orm-${{ env.VERSION }}-linux-amd64.tar.gz
        chmod +x redi-orm-${{ env.VERSION }}-linux-amd64
        sudo mv redi-orm-${{ env.VERSION }}-linux-amd64 /usr/local/bin/redi-orm
        ```

        **Linux (ARM64)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-orm-${{ env.VERSION }}-linux-arm64.tar.gz
        tar -xzf redi-orm-${{ env.VERSION }}-linux-arm64.tar.gz
        chmod +x redi-orm-${{ env.VERSION }}-linux-arm64
        sudo mv redi-orm-${{ env.VERSION }}-linux-arm64 /usr/local/bin/redi-orm
        ```

        **macOS (Intel)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-orm-${{ env.VERSION }}-darwin-amd64.tar.gz
        tar -xzf redi-orm-${{ env.VERSION }}-darwin-amd64.tar.gz
        chmod +x redi-orm-${{ env.VERSION }}-darwin-amd64
        sudo mv redi-orm-${{ env.VERSION }}-darwin-amd64 /usr/local/bin/redi-orm
        ```

        **macOS (Apple Silicon)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-orm-${{ env.VERSION }}-darwin-arm64.tar.gz
        tar -xzf redi-orm-${{ env.VERSION }}-darwin-arm64.tar.gz
        chmod +x redi-orm-${{ env.VERSION }}-darwin-arm64
        sudo mv redi-orm-${{ env.VERSION }}-darwin-arm64 /usr/local/bin/redi-orm
        ```

        **Windows (AMD64)**:
        1. Download `redi-orm-${{ env.VERSION }}-windows-amd64.zip`
        2. Extract the ZIP file
        3. Add the extracted `redi-orm-${{ env.VERSION }}-windows-amd64.exe` to your PATH or rename it to `redi-orm.exe`

        ### Verify Installation

        ```bash
        redi-orm version
        ```

        ### Installing redi-mcp

        Choose the appropriate MCP binary for your platform:

        **Linux (AMD64)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-mcp-${{ env.VERSION }}-linux-amd64.tar.gz
        tar -xzf redi-mcp-${{ env.VERSION }}-linux-amd64.tar.gz
        chmod +x redi-mcp-${{ env.VERSION }}-linux-amd64
        sudo mv redi-mcp-${{ env.VERSION }}-linux-amd64 /usr/local/bin/redi-mcp
        ```

        **macOS (Intel)**:
        ```bash
        wget https://github.com/rediwo/redi-orm/releases/download/${{ env.VERSION }}/redi-mcp-${{ env.VERSION }}-darwin-amd64.tar.gz
        tar -xzf redi-mcp-${{ env.VERSION }}-darwin-amd64.tar.gz
        chmod +x redi-mcp-${{ env.VERSION }}-darwin-amd64
        sudo mv redi-mcp-${{ env.VERSION }}-darwin-amd64 /usr/local/bin/redi-mcp
        ```

        **Windows**:
        1. Download `redi-mcp-${{ env.VERSION }}-windows-amd64.zip`
        2. Extract and add to PATH

        Verify with:
        ```bash
        redi-mcp version
        ```

        ## Quick Start

        ### 1. Create a schema file (schema.prisma)
        ```prisma
        model User {
          id    Int     @id @default(autoincrement())
          name  String
          email String  @unique
          posts Post[]
        }

        model Post {
          id       Int    @id @default(autoincrement())
          title    String
          content  String?
          authorId Int
          author   User   @relation(fields: [authorId], references: [id])
        }
        ```

        ### 2. Run migrations
        ```bash
        # Auto-migrate (development)
        redi-orm migrate --db=sqlite://./app.db --schema=./schema.prisma

        # Or generate migration files (production)
        redi-orm migrate:generate --db=sqlite://./app.db --schema=./schema.prisma --name="initial"
        ```

        ### 3. Use JavaScript API
        ```javascript
        // app.js
        const { fromUri } = require('redi/orm');

        const db = fromUri('sqlite://./app.db');
        await db.connect();

        // Load schema
        await db.loadSchemaFrom('./schema.prisma');
        await db.syncSchemas();

        // Create a user
        const user = await db.models.User.create({
          data: { name: 'Alice', email: 'alice@example.com' }
        });

        // Create a post
        const post = await db.models.Post.create({
          data: {
            title: 'Hello World',
            content: 'My first post',
            authorId: user.id
          }
        });

        // Query with relations
        const userWithPosts = await db.models.User.findUnique({
          where: { id: user.id },
          include: { posts: true }
        });

        console.log(userWithPosts);
        ```

        ### 4. Run the script
        ```bash
        redi-orm run app.js
        ```

        ## MCP Quick Start

        ### For Claude Desktop
        Add to `~/.claude/claude_desktop_config.json`:
        ```json
        {
          "mcpServers": {
            "database": {
              "command": "redi-mcp",
              "args": ["--db=sqlite://./app.db", "--schema=./schema.prisma"]
            }
          }
        }
        ```

        ### For Cursor/Windsurf
        Add to `.cursor/config.json`:
        ```json
        {
          "mcpServers": {
            "orm-mcp": {
              "url": "http://localhost:8080"
            }
          }
        }
        ```

        Then start the MCP server:
        ```bash
        redi-mcp --db=sqlite://./app.db --schema=./schema.prisma --port=8080
        ```

        ## Security

        All release assets include SHA256 checksums for verification. You can verify the integrity of your download:

        ```bash
        # Linux/macOS
        sha256sum -c redi-orm-${{ env.VERSION }}-linux-amd64.tar.gz.sha256

        # Windows (PowerShell)
        Get-FileHash redi-orm-${{ env.VERSION }}-windows-amd64.zip -Algorithm SHA256
        ```

        ## Documentation

        - [GitHub Repository](https://github.com/rediwo/redi-orm)
        - [RediORM CLI Guide](https://github.com/rediwo/redi-orm/blob/main/cmd/redi-orm/README.md)
        - [RediMCP Guide](https://github.com/rediwo/redi-orm/blob/main/cmd/redi-mcp/README.md)
        - [Examples](https://github.com/rediwo/redi-orm/tree/main/examples)

        ---

        **Full Changelog**: https://github.com/rediwo/redi-orm/compare/v0.0.1...${{ env.VERSION }}
        EOF

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: RediORM ${{ env.VERSION }}
        body_path: release_notes.md
        files: |
          release-assets/*.zip
          release-assets/*.tar.gz
          release-assets/*.sha256
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}